services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    build:
      context: .
      dockerfile: images/Dockerfile.minitwit
    container_name: minitwit
    stdin_open: true
    tty: true
    networks:
      - main
    depends_on:
      - itusqlimage
    ports:
        - '4567:4567'
    volumes:
      - '/tmp/minitwit.db:/tmp/minitwit.db'
    environment:
      - ENV=dev
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}


  itusqlimage:
    image: ${DOCKER_USERNAME}/dbimage
    build:
      context: .
      dockerfile: images/Dockerfile.mysql
    container_name: minitwit_db
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    networks:
      - main

networks:
  main:
