{
 "title": "Minitwit System",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Return Codes [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100* (sum(http_server_requests_total) by (code)/ on() group_left() sum(http_server_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(sum(http_server_requests_total{path=~\".*msgs.*\"}), \"msgs\", \"msgs\", \"name\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(http_server_requests_total{path=~\".*register.*\"}), \"register\", \"register\", \"name\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(http_server_requests_total{path=~\".*fllws.*\"}), \"fllws\", \"fllws\", \"name\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Website Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{instance=\"minitwit:4567\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}