services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage
    stdin_open: true
    tty: true
    restart: always
    networks:
      - main
    depends_on:
      - database
    ports:
      - target: 4567
        published: 4567
        protocol: tcp
        mode: ingress
    environment:
      - RACK_ENV=production
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure

  database:
    image: postgres:17.4-bookworm
    restart: always
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: minitwit
      POSTGRES_INITDB_ARGS: "-A md5"
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    networks:
      - main
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.2'

  grafana:
    image: grafana/grafana:11.5.2
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/alerting:/etc/grafana/provisioning/alerting
    ports:
      - "3000:3000"
    networks:
      - main
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:7.2-alpine
    restart: always
    networks:
      - main
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  main:
    driver: overlay
    name: 'minitwit_main'

volumes:
  pgdata:
    driver: local
  grafana-data:
    driver: local
  redis-data:
    driver: local
