FROM python:3.13-alpine

# Install Firefox and required tools using apk
RUN apk add --no-cache \
    firefox-esr \
    tar=1.35-r2 \
    wget=1.25.0-r0 \
    # Download and install the latest geckodriver (recommended version for Firefox 136.0.1)
    && wget -nv https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz && \
    tar -xzf geckodriver-v0.36.0-linux64.tar.gz && \
    mv geckodriver /usr/local/bin/ && \
    chmod +x /usr/local/bin/geckodriver

WORKDIR /test

COPY requirements.txt .
RUN pip install --no-cache-dir  -r requirements.txt 

COPY remote_files/schema.sql .
COPY src/test .

ENTRYPOINT ["pytest"]
