FROM python:3.13-alpine

# Install Firefox and required tools using apk
RUN apk add --no-cache \
    firefox-esr \
    wget \
    tar

RUN /usr/bin/firefox-esr --version

# Download and install the latest geckodriver (recommended version for Firefox 136.0.1)
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz && \
    tar -xzf geckodriver-v0.36.0-linux64.tar.gz && \
    mv geckodriver /usr/local/bin/ && \
    chmod +x /usr/local/bin/geckodriver

WORKDIR /test

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY remote_files/schema.sql .
COPY src/test .

ENTRYPOINT ["pytest"]
