FROM python:3.7-alpine

# RUN mkdir /minitwit-tests


# COPY minitwit_tests.py /minitwit-tests/

WORKDIR /minitwit-tests/

COPY requirements.txt .
COPY /test . 

RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["pytest"]
