apiVersion: 1
contactPoints:
    - orgId: 1
      name: Discord
      receivers:
        - uid: feghjtaj9ejnkd
          type: discord
          settings:
            message: '{{ template "discord.default.message" . }}'
            url: |
              $CONTACT_URL
            use_discord_username: true
          disableResolveMessage: false
