name: CI

on: [push, pull_request]

jobs:
  bundler-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"

      - name: Install dependencies
        run: bundle install

      - name: Run Bundler Audit
        run: bundle exec bundler-audit check --update
