name: Continuous Testing

on:
  pull_request:

  # allow manual triggers for now too
  workflow_dispatch:

  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          docker compose -f dev-compose.yml up --build --abort-on-container-exit
        env:
          DB_USER: "test"
          DB_PWD: "test"
          APP_ENV: "test"
